#include "s21_common.h"

#ifdef __APPLE__
#define OS_NAME "macOS"

static const char *macOS_error_messages[] = {
    "Unknown error: -300",
    "Unknown error: -299",
    "Unknown error: -298",
    "Unknown error: -297",
    "Unknown error: -296",
    "Unknown error: -295",
    "Unknown error: -294",
    "Unknown error: -293",
    "Unknown error: -292",
    "Unknown error: -291",
    "Unknown error: -290",
    "Unknown error: -289",
    "Unknown error: -288",
    "Unknown error: -287",
    "Unknown error: -286",
    "Unknown error: -285",
    "Unknown error: -284",
    "Unknown error: -283",
    "Unknown error: -282",
    "Unknown error: -281",
    "Unknown error: -280",
    "Unknown error: -279",
    "Unknown error: -278",
    "Unknown error: -277",
    "Unknown error: -276",
    "Unknown error: -275",
    "Unknown error: -274",
    "Unknown error: -273",
    "Unknown error: -272",
    "Unknown error: -271",
    "Unknown error: -270",
    "Unknown error: -269",
    "Unknown error: -268",
    "Unknown error: -267",
    "Unknown error: -266",
    "Unknown error: -265",
    "Unknown error: -264",
    "Unknown error: -263",
    "Unknown error: -262",
    "Unknown error: -261",
    "Unknown error: -260",
    "Unknown error: -259",
    "Unknown error: -258",
    "Unknown error: -257",
    "Unknown error: -256",
    "Unknown error: -255",
    "Unknown error: -254",
    "Unknown error: -253",
    "Unknown error: -252",
    "Unknown error: -251",
    "Unknown error: -250",
    "Unknown error: -249",
    "Unknown error: -248",
    "Unknown error: -247",
    "Unknown error: -246",
    "Unknown error: -245",
    "Unknown error: -244",
    "Unknown error: -243",
    "Unknown error: -242",
    "Unknown error: -241",
    "Unknown error: -240",
    "Unknown error: -239",
    "Unknown error: -238",
    "Unknown error: -237",
    "Unknown error: -236",
    "Unknown error: -235",
    "Unknown error: -234",
    "Unknown error: -233",
    "Unknown error: -232",
    "Unknown error: -231",
    "Unknown error: -230",
    "Unknown error: -229",
    "Unknown error: -228",
    "Unknown error: -227",
    "Unknown error: -226",
    "Unknown error: -225",
    "Unknown error: -224",
    "Unknown error: -223",
    "Unknown error: -222",
    "Unknown error: -221",
    "Unknown error: -220",
    "Unknown error: -219",
    "Unknown error: -218",
    "Unknown error: -217",
    "Unknown error: -216",
    "Unknown error: -215",
    "Unknown error: -214",
    "Unknown error: -213",
    "Unknown error: -212",
    "Unknown error: -211",
    "Unknown error: -210",
    "Unknown error: -209",
    "Unknown error: -208",
    "Unknown error: -207",
    "Unknown error: -206",
    "Unknown error: -205",
    "Unknown error: -204",
    "Unknown error: -203",
    "Unknown error: -202",
    "Unknown error: -201",
    "Unknown error: -200",
    "Unknown error: -199",
    "Unknown error: -198",
    "Unknown error: -197",
    "Unknown error: -196",
    "Unknown error: -195",
    "Unknown error: -194",
    "Unknown error: -193",
    "Unknown error: -192",
    "Unknown error: -191",
    "Unknown error: -190",
    "Unknown error: -189",
    "Unknown error: -188",
    "Unknown error: -187",
    "Unknown error: -186",
    "Unknown error: -185",
    "Unknown error: -184",
    "Unknown error: -183",
    "Unknown error: -182",
    "Unknown error: -181",
    "Unknown error: -180",
    "Unknown error: -179",
    "Unknown error: -178",
    "Unknown error: -177",
    "Unknown error: -176",
    "Unknown error: -175",
    "Unknown error: -174",
    "Unknown error: -173",
    "Unknown error: -172",
    "Unknown error: -171",
    "Unknown error: -170",
    "Unknown error: -169",
    "Unknown error: -168",
    "Unknown error: -167",
    "Unknown error: -166",
    "Unknown error: -165",
    "Unknown error: -164",
    "Unknown error: -163",
    "Unknown error: -162",
    "Unknown error: -161",
    "Unknown error: -160",
    "Unknown error: -159",
    "Unknown error: -158",
    "Unknown error: -157",
    "Unknown error: -156",
    "Unknown error: -155",
    "Unknown error: -154",
    "Unknown error: -153",
    "Unknown error: -152",
    "Unknown error: -151",
    "Unknown error: -150",
    "Unknown error: -149",
    "Unknown error: -148",
    "Unknown error: -147",
    "Unknown error: -146",
    "Unknown error: -145",
    "Unknown error: -144",
    "Unknown error: -143",
    "Unknown error: -142",
    "Unknown error: -141",
    "Unknown error: -140",
    "Unknown error: -139",
    "Unknown error: -138",
    "Unknown error: -137",
    "Unknown error: -136",
    "Unknown error: -135",
    "Unknown error: -134",
    "Unknown error: -133",
    "Unknown error: -132",
    "Unknown error: -131",
    "Unknown error: -130",
    "Unknown error: -129",
    "Unknown error: -128",
    "Unknown error: -127",
    "Unknown error: -126",
    "Unknown error: -125",
    "Unknown error: -124",
    "Unknown error: -123",
    "Unknown error: -122",
    "Unknown error: -121",
    "Unknown error: -120",
    "Unknown error: -119",
    "Unknown error: -118",
    "Unknown error: -117",
    "Unknown error: -116",
    "Unknown error: -115",
    "Unknown error: -114",
    "Unknown error: -113",
    "Unknown error: -112",
    "Unknown error: -111",
    "Unknown error: -110",
    "Unknown error: -109",
    "Unknown error: -108",
    "Unknown error: -107",
    "Unknown error: -106",
    "Unknown error: -105",
    "Unknown error: -104",
    "Unknown error: -103",
    "Unknown error: -102",
    "Unknown error: -101",
    "Unknown error: -100",
    "Unknown error: -99",
    "Unknown error: -98",
    "Unknown error: -97",
    "Unknown error: -96",
    "Unknown error: -95",
    "Unknown error: -94",
    "Unknown error: -93",
    "Unknown error: -92",
    "Unknown error: -91",
    "Unknown error: -90",
    "Unknown error: -89",
    "Unknown error: -88",
    "Unknown error: -87",
    "Unknown error: -86",
    "Unknown error: -85",
    "Unknown error: -84",
    "Unknown error: -83",
    "Unknown error: -82",
    "Unknown error: -81",
    "Unknown error: -80",
    "Unknown error: -79",
    "Unknown error: -78",
    "Unknown error: -77",
    "Unknown error: -76",
    "Unknown error: -75",
    "Unknown error: -74",
    "Unknown error: -73",
    "Unknown error: -72",
    "Unknown error: -71",
    "Unknown error: -70",
    "Unknown error: -69",
    "Unknown error: -68",
    "Unknown error: -67",
    "Unknown error: -66",
    "Unknown error: -65",
    "Unknown error: -64",
    "Unknown error: -63",
    "Unknown error: -62",
    "Unknown error: -61",
    "Unknown error: -60",
    "Unknown error: -59",
    "Unknown error: -58",
    "Unknown error: -57",
    "Unknown error: -56",
    "Unknown error: -55",
    "Unknown error: -54",
    "Unknown error: -53",
    "Unknown error: -52",
    "Unknown error: -51",
    "Unknown error: -50",
    "Unknown error: -49",
    "Unknown error: -48",
    "Unknown error: -47",
    "Unknown error: -46",
    "Unknown error: -45",
    "Unknown error: -44",
    "Unknown error: -43",
    "Unknown error: -42",
    "Unknown error: -41",
    "Unknown error: -40",
    "Unknown error: -39",
    "Unknown error: -38",
    "Unknown error: -37",
    "Unknown error: -36",
    "Unknown error: -35",
    "Unknown error: -34",
    "Unknown error: -33",
    "Unknown error: -32",
    "Unknown error: -31",
    "Unknown error: -30",
    "Unknown error: -29",
    "Unknown error: -28",
    "Unknown error: -27",
    "Unknown error: -26",
    "Unknown error: -25",
    "Unknown error: -24",
    "Unknown error: -23",
    "Unknown error: -22",
    "Unknown error: -21",
    "Unknown error: -20",
    "Unknown error: -19",
    "Unknown error: -18",
    "Unknown error: -17",
    "Unknown error: -16",
    "Unknown error: -15",
    "Unknown error: -14",
    "Unknown error: -13",
    "Unknown error: -12",
    "Unknown error: -11",
    "Unknown error: -10",
    "Unknown error: -9",
    "Unknown error: -8",
    "Unknown error: -7",
    "Unknown error: -6",
    "Unknown error: -5",
    "Unknown error: -4",
    "Unknown error: -3",
    "Unknown error: -2",
    "Unknown error: -1",
    "Undefined error: 0",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "Device not configured",
    "Argument list too long",
    "Exec format error",
    "Bad file descriptor",
    "No child processes",
    "Resource deadlock avoided",
    "Cannot allocate memory",
    "Permission denied",
    "Bad address",
    "Block device required",
    "Resource busy",
    "File exists",
    "Cross-device link",
    "Operation not supported by device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many open files in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "No space left on device",
    "Illegal seek",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Numerical argument out of domain",
    "Result too large",
    "Resource temporarily unavailable",
    "Operation now in progress",
    "Operation already in progress",
    "Socket operation on non-socket",
    "Destination address required",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not available",
    "Protocol not supported",
    "Socket type not supported",
    "Operation not supported",
    "Protocol family not supported",
    "Address family not supported by protocol family",
    "Address already in use",
    "Can't assign requested address",
    "Network is down",
    "Network is unreachable",
    "Network dropped connection on reset",
    "Software caused connection abort",
    "Connection reset by peer",
    "No buffer space available",
    "Socket is already connected",
    "Socket is not connected",
    "Can't send after socket shutdown",
    "Too many references: can't splice",
    "Operation timed out",
    "Connection refused",
    "Too many levels of symbolic links",
    "File name too long",
    "Host is down",
    "No route to host",
    "Directory not empty",
    "Too many processes",
    "Too many users",
    "Disc quota exceeded",
    "Stale NFS file handle",
    "Too many levels of remote in path",
    "RPC struct is bad",
    "RPC version wrong",
    "RPC prog. not avail",
    "Program version wrong",
    "Bad procedure for program",
    "No locks available",
    "Function not implemented",
    "Inappropriate file type or format",
    "Authentication error",
    "Need authenticator",
    "Device power is off",
    "Device error",
    "Value too large to be stored in data type",
    "Bad executable (or shared library)",
    "Bad CPU type in executable",
    "Shared library version mismatch",
    "Malformed Mach-o file",
    "Operation canceled",
    "Identifier removed",
    "No message of desired type",
    "Illegal byte sequence",
    "Attribute not found",
    "Bad message",
    "EMULTIHOP (Reserved)",
    "No message available on STREAM",
    "ENOLINK (Reserved)",
    "No STREAM resources",
    "Not a STREAM",
    "Protocol error",
    "STREAM ioctl timeout",
    "Operation not supported on socket",
    "Policy not found",
    "State not recoverable",
    "Previous owner died",
    "Interface output queue is full",
    "Unknown error: 107",
    "Unknown error: 108",
    "Unknown error: 109",
    "Unknown error: 110",
    "Unknown error: 111",
    "Unknown error: 112",
    "Unknown error: 113",
    "Unknown error: 114",
    "Unknown error: 115",
    "Unknown error: 116",
    "Unknown error: 117",
    "Unknown error: 118",
    "Unknown error: 119",
    "Unknown error: 120",
    "Unknown error: 121",
    "Unknown error: 122",
    "Unknown error: 123",
    "Unknown error: 124",
    "Unknown error: 125",
    "Unknown error: 126",
    "Unknown error: 127",
    "Unknown error: 128",
    "Unknown error: 129",
    "Unknown error: 130",
    "Unknown error: 131",
    "Unknown error: 132",
    "Unknown error: 133",
    "Unknown error: 134",
    "Unknown error: 135",
    "Unknown error: 136",
    "Unknown error: 137",
    "Unknown error: 138",
    "Unknown error: 139",
    "Unknown error: 140",
    "Unknown error: 141",
    "Unknown error: 142",
    "Unknown error: 143",
    "Unknown error: 144",
    "Unknown error: 145",
    "Unknown error: 146",
    "Unknown error: 147",
    "Unknown error: 148",
    "Unknown error: 149",
    "Unknown error: 150",
    "Unknown error: 151",
    "Unknown error: 152",
    "Unknown error: 153",
    "Unknown error: 154",
    "Unknown error: 155",
    "Unknown error: 156",
    "Unknown error: 157",
    "Unknown error: 158",
    "Unknown error: 159",
    "Unknown error: 160",
    "Unknown error: 161",
    "Unknown error: 162",
    "Unknown error: 163",
    "Unknown error: 164",
    "Unknown error: 165",
    "Unknown error: 166",
    "Unknown error: 167",
    "Unknown error: 168",
    "Unknown error: 169",
    "Unknown error: 170",
    "Unknown error: 171",
    "Unknown error: 172",
    "Unknown error: 173",
    "Unknown error: 174",
    "Unknown error: 175",
    "Unknown error: 176",
    "Unknown error: 177",
    "Unknown error: 178",
    "Unknown error: 179",
    "Unknown error: 180",
    "Unknown error: 181",
    "Unknown error: 182",
    "Unknown error: 183",
    "Unknown error: 184",
    "Unknown error: 185",
    "Unknown error: 186",
    "Unknown error: 187",
    "Unknown error: 188",
    "Unknown error: 189",
    "Unknown error: 190",
    "Unknown error: 191",
    "Unknown error: 192",
    "Unknown error: 193",
    "Unknown error: 194",
    "Unknown error: 195",
    "Unknown error: 196",
    "Unknown error: 197",
    "Unknown error: 198",
    "Unknown error: 199",
    "Unknown error: 200",
    "Unknown error: 201",
    "Unknown error: 202",
    "Unknown error: 203",
    "Unknown error: 204",
    "Unknown error: 205",
    "Unknown error: 206",
    "Unknown error: 207",
    "Unknown error: 208",
    "Unknown error: 209",
    "Unknown error: 210",
    "Unknown error: 211",
    "Unknown error: 212",
    "Unknown error: 213",
    "Unknown error: 214",
    "Unknown error: 215",
    "Unknown error: 216",
    "Unknown error: 217",
    "Unknown error: 218",
    "Unknown error: 219",
    "Unknown error: 220",
    "Unknown error: 221",
    "Unknown error: 222",
    "Unknown error: 223",
    "Unknown error: 224",
    "Unknown error: 225",
    "Unknown error: 226",
    "Unknown error: 227",
    "Unknown error: 228",
    "Unknown error: 229",
    "Unknown error: 230",
    "Unknown error: 231",
    "Unknown error: 232",
    "Unknown error: 233",
    "Unknown error: 234",
    "Unknown error: 235",
    "Unknown error: 236",
    "Unknown error: 237",
    "Unknown error: 238",
    "Unknown error: 239",
    "Unknown error: 240",
    "Unknown error: 241",
    "Unknown error: 242",
    "Unknown error: 243",
    "Unknown error: 244",
    "Unknown error: 245",
    "Unknown error: 246",
    "Unknown error: 247",
    "Unknown error: 248",
    "Unknown error: 249",
    "Unknown error: 250",
    "Unknown error: 251",
    "Unknown error: 252",
    "Unknown error: 253",
    "Unknown error: 254",
    "Unknown error: 255",
    "Unknown error: 256",
    "Unknown error: 257",
    "Unknown error: 258",
    "Unknown error: 259",
    "Unknown error: 260",
    "Unknown error: 261",
    "Unknown error: 262",
    "Unknown error: 263",
    "Unknown error: 264",
    "Unknown error: 265",
    "Unknown error: 266",
    "Unknown error: 267",
    "Unknown error: 268",
    "Unknown error: 269",
    "Unknown error: 270",
    "Unknown error: 271",
    "Unknown error: 272",
    "Unknown error: 273",
    "Unknown error: 274",
    "Unknown error: 275",
    "Unknown error: 276",
    "Unknown error: 277",
    "Unknown error: 278",
    "Unknown error: 279",
    "Unknown error: 280",
    "Unknown error: 281",
    "Unknown error: 282",
    "Unknown error: 283",
    "Unknown error: 284",
    "Unknown error: 285",
    "Unknown error: 286",
    "Unknown error: 287",
    "Unknown error: 288",
    "Unknown error: 289",
    "Unknown error: 290",
    "Unknown error: 291",
    "Unknown error: 292",
    "Unknown error: 293",
    "Unknown error: 294",
    "Unknown error: 295",
    "Unknown error: 296",
    "Unknown error: 297",
    "Unknown error: 298",
    "Unknown error: 299"};

#define NUM_MACOS_ERRORS \
  (sizeof(macOS_error_messages) / sizeof(macOS_error_messages[0]))

#elif defined(__linux__)
#define OS_NAME "Linux"

static const char *linux_error_messages[] = {
    "Unknown error -300",
    "Unknown error -299",
    "Unknown error -298",
    "Unknown error -297",
    "Unknown error -296",
    "Unknown error -295",
    "Unknown error -294",
    "Unknown error -293",
    "Unknown error -292",
    "Unknown error -291",
    "Unknown error -290",
    "Unknown error -289",
    "Unknown error -288",
    "Unknown error -287",
    "Unknown error -286",
    "Unknown error -285",
    "Unknown error -284",
    "Unknown error -283",
    "Unknown error -282",
    "Unknown error -281",
    "Unknown error -280",
    "Unknown error -279",
    "Unknown error -278",
    "Unknown error -277",
    "Unknown error -276",
    "Unknown error -275",
    "Unknown error -274",
    "Unknown error -273",
    "Unknown error -272",
    "Unknown error -271",
    "Unknown error -270",
    "Unknown error -269",
    "Unknown error -268",
    "Unknown error -267",
    "Unknown error -266",
    "Unknown error -265",
    "Unknown error -264",
    "Unknown error -263",
    "Unknown error -262",
    "Unknown error -261",
    "Unknown error -260",
    "Unknown error -259",
    "Unknown error -258",
    "Unknown error -257",
    "Unknown error -256",
    "Unknown error -255",
    "Unknown error -254",
    "Unknown error -253",
    "Unknown error -252",
    "Unknown error -251",
    "Unknown error -250",
    "Unknown error -249",
    "Unknown error -248",
    "Unknown error -247",
    "Unknown error -246",
    "Unknown error -245",
    "Unknown error -244",
    "Unknown error -243",
    "Unknown error -242",
    "Unknown error -241",
    "Unknown error -240",
    "Unknown error -239",
    "Unknown error -238",
    "Unknown error -237",
    "Unknown error -236",
    "Unknown error -235",
    "Unknown error -234",
    "Unknown error -233",
    "Unknown error -232",
    "Unknown error -231",
    "Unknown error -230",
    "Unknown error -229",
    "Unknown error -228",
    "Unknown error -227",
    "Unknown error -226",
    "Unknown error -225",
    "Unknown error -224",
    "Unknown error -223",
    "Unknown error -222",
    "Unknown error -221",
    "Unknown error -220",
    "Unknown error -219",
    "Unknown error -218",
    "Unknown error -217",
    "Unknown error -216",
    "Unknown error -215",
    "Unknown error -214",
    "Unknown error -213",
    "Unknown error -212",
    "Unknown error -211",
    "Unknown error -210",
    "Unknown error -209",
    "Unknown error -208",
    "Unknown error -207",
    "Unknown error -206",
    "Unknown error -205",
    "Unknown error -204",
    "Unknown error -203",
    "Unknown error -202",
    "Unknown error -201",
    "Unknown error -200",
    "Unknown error -199",
    "Unknown error -198",
    "Unknown error -197",
    "Unknown error -196",
    "Unknown error -195",
    "Unknown error -194",
    "Unknown error -193",
    "Unknown error -192",
    "Unknown error -191",
    "Unknown error -190",
    "Unknown error -189",
    "Unknown error -188",
    "Unknown error -187",
    "Unknown error -186",
    "Unknown error -185",
    "Unknown error -184",
    "Unknown error -183",
    "Unknown error -182",
    "Unknown error -181",
    "Unknown error -180",
    "Unknown error -179",
    "Unknown error -178",
    "Unknown error -177",
    "Unknown error -176",
    "Unknown error -175",
    "Unknown error -174",
    "Unknown error -173",
    "Unknown error -172",
    "Unknown error -171",
    "Unknown error -170",
    "Unknown error -169",
    "Unknown error -168",
    "Unknown error -167",
    "Unknown error -166",
    "Unknown error -165",
    "Unknown error -164",
    "Unknown error -163",
    "Unknown error -162",
    "Unknown error -161",
    "Unknown error -160",
    "Unknown error -159",
    "Unknown error -158",
    "Unknown error -157",
    "Unknown error -156",
    "Unknown error -155",
    "Unknown error -154",
    "Unknown error -153",
    "Unknown error -152",
    "Unknown error -151",
    "Unknown error -150",
    "Unknown error -149",
    "Unknown error -148",
    "Unknown error -147",
    "Unknown error -146",
    "Unknown error -145",
    "Unknown error -144",
    "Unknown error -143",
    "Unknown error -142",
    "Unknown error -141",
    "Unknown error -140",
    "Unknown error -139",
    "Unknown error -138",
    "Unknown error -137",
    "Unknown error -136",
    "Unknown error -135",
    "Unknown error -134",
    "Unknown error -133",
    "Unknown error -132",
    "Unknown error -131",
    "Unknown error -130",
    "Unknown error -129",
    "Unknown error -128",
    "Unknown error -127",
    "Unknown error -126",
    "Unknown error -125",
    "Unknown error -124",
    "Unknown error -123",
    "Unknown error -122",
    "Unknown error -121",
    "Unknown error -120",
    "Unknown error -119",
    "Unknown error -118",
    "Unknown error -117",
    "Unknown error -116",
    "Unknown error -115",
    "Unknown error -114",
    "Unknown error -113",
    "Unknown error -112",
    "Unknown error -111",
    "Unknown error -110",
    "Unknown error -109",
    "Unknown error -108",
    "Unknown error -107",
    "Unknown error -106",
    "Unknown error -105",
    "Unknown error -104",
    "Unknown error -103",
    "Unknown error -102",
    "Unknown error -101",
    "Unknown error -100",
    "Unknown error -99",
    "Unknown error -98",
    "Unknown error -97",
    "Unknown error -96",
    "Unknown error -95",
    "Unknown error -94",
    "Unknown error -93",
    "Unknown error -92",
    "Unknown error -91",
    "Unknown error -90",
    "Unknown error -89",
    "Unknown error -88",
    "Unknown error -87",
    "Unknown error -86",
    "Unknown error -85",
    "Unknown error -84",
    "Unknown error -83",
    "Unknown error -82",
    "Unknown error -81",
    "Unknown error -80",
    "Unknown error -79",
    "Unknown error -78",
    "Unknown error -77",
    "Unknown error -76",
    "Unknown error -75",
    "Unknown error -74",
    "Unknown error -73",
    "Unknown error -72",
    "Unknown error -71",
    "Unknown error -70",
    "Unknown error -69",
    "Unknown error -68",
    "Unknown error -67",
    "Unknown error -66",
    "Unknown error -65",
    "Unknown error -64",
    "Unknown error -63",
    "Unknown error -62",
    "Unknown error -61",
    "Unknown error -60",
    "Unknown error -59",
    "Unknown error -58",
    "Unknown error -57",
    "Unknown error -56",
    "Unknown error -55",
    "Unknown error -54",
    "Unknown error -53",
    "Unknown error -52",
    "Unknown error -51",
    "Unknown error -50",
    "Unknown error -49",
    "Unknown error -48",
    "Unknown error -47",
    "Unknown error -46",
    "Unknown error -45",
    "Unknown error -44",
    "Unknown error -43",
    "Unknown error -42",
    "Unknown error -41",
    "Unknown error -40",
    "Unknown error -39",
    "Unknown error -38",
    "Unknown error -37",
    "Unknown error -36",
    "Unknown error -35",
    "Unknown error -34",
    "Unknown error -33",
    "Unknown error -32",
    "Unknown error -31",
    "Unknown error -30",
    "Unknown error -29",
    "Unknown error -28",
    "Unknown error -27",
    "Unknown error -26",
    "Unknown error -25",
    "Unknown error -24",
    "Unknown error -23",
    "Unknown error -22",
    "Unknown error -21",
    "Unknown error -20",
    "Unknown error -19",
    "Unknown error -18",
    "Unknown error -17",
    "Unknown error -16",
    "Unknown error -15",
    "Unknown error -14",
    "Unknown error -13",
    "Unknown error -12",
    "Unknown error -11",
    "Unknown error -10",
    "Unknown error -9",
    "Unknown error -8",
    "Unknown error -7",
    "Unknown error -6",
    "Unknown error -5",
    "Unknown error -4",
    "Unknown error -3",
    "Unknown error -2",
    "Unknown error -1",
    "Success",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "No such device or address",
    "Argument list too long",
    "Exec format error",
    "Bad file descriptor",
    "No child processes",
    "Resource temporarily unavailable",
    "Cannot allocate memory",
    "Permission denied",
    "Bad address",
    "Block device required",
    "Device or resource busy",
    "File exists",
    "Invalid cross-device link",
    "No such device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many open files in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "No space left on device",
    "Illegal seek",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Numerical argument out of domain",
    "Numerical result out of range",
    "Resource deadlock avoided",
    "File name too long",
    "No locks available",
    "Function not implemented",
    "Directory not empty",
    "Too many levels of symbolic links",
    "Unknown error 41",
    "No message of desired type",
    "Identifier removed",
    "Channel number out of range",
    "Level 2 not synchronized",
    "Level 3 halted",
    "Level 3 reset",
    "Link number out of range",
    "Protocol driver not attached",
    "No CSI structure available",
    "Level 2 halted",
    "Invalid exchange",
    "Invalid request descriptor",
    "Exchange full",
    "No anode",
    "Invalid request code",
    "Invalid slot",
    "Unknown error 58",
    "Bad font file format",
    "Device not a stream",
    "No data available",
    "Timer expired",
    "Out of streams resources",
    "Machine is not on the network",
    "Package not installed",
    "Object is remote",
    "Link has been severed",
    "Advertise error",
    "Srmount error",
    "Communication error on send",
    "Protocol error",
    "Multihop attempted",
    "RFS specific error",
    "Bad message",
    "Value too large for defined data type",
    "Name not unique on network",
    "File descriptor in bad state",
    "Remote address changed",
    "Can not access a needed shared library",
    "Accessing a corrupted shared library",
    ".lib section in a.out corrupted",
    "Attempting to link in too many shared libraries",
    "Cannot exec a shared library directly",
    "Invalid or incomplete multibyte or wide character",
    "Interrupted system call should be restarted",
    "Streams pipe error",
    "Too many users",
    "Socket operation on non-socket",
    "Destination address required",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not available",
    "Protocol not supported",
    "Socket type not supported",
    "Operation not supported",
    "Protocol family not supported",
    "Address family not supported by protocol",
    "Address already in use",
    "Cannot assign requested address",
    "Network is down",
    "Network is unreachable",
    "Network dropped connection on reset",
    "Software caused connection abort",
    "Connection reset by peer",
    "No buffer space available",
    "Transport endpoint is already connected",
    "Transport endpoint is not connected",
    "Cannot send after transport endpoint shutdown",
    "Too many references: cannot splice",
    "Connection timed out",
    "Connection refused",
    "Host is down",
    "No route to host",
    "Operation already in progress",
    "Operation now in progress",
    "Stale file handle",
    "Structure needs cleaning",
    "Not a XENIX named type file",
    "No XENIX semaphores available",
    "Is a named type file",
    "Remote I/O error",
    "Disk quota exceeded",
    "No medium found",
    "Wrong medium type",
    "Operation canceled",
    "Required key not available",
    "Key has expired",
    "Key has been revoked",
    "Key was rejected by service",
    "Owner died",
    "State not recoverable",
    "Operation not possible due to RF-kill",
    "Memory page has hardware error",
    "Unknown error 134",
    "Unknown error 135",
    "Unknown error 136",
    "Unknown error 137",
    "Unknown error 138",
    "Unknown error 139",
    "Unknown error 140",
    "Unknown error 141",
    "Unknown error 142",
    "Unknown error 143",
    "Unknown error 144",
    "Unknown error 145",
    "Unknown error 146",
    "Unknown error 147",
    "Unknown error 148",
    "Unknown error 149",
    "Unknown error 150",
    "Unknown error 151",
    "Unknown error 152",
    "Unknown error 153",
    "Unknown error 154",
    "Unknown error 155",
    "Unknown error 156",
    "Unknown error 157",
    "Unknown error 158",
    "Unknown error 159",
    "Unknown error 160",
    "Unknown error 161",
    "Unknown error 162",
    "Unknown error 163",
    "Unknown error 164",
    "Unknown error 165",
    "Unknown error 166",
    "Unknown error 167",
    "Unknown error 168",
    "Unknown error 169",
    "Unknown error 170",
    "Unknown error 171",
    "Unknown error 172",
    "Unknown error 173",
    "Unknown error 174",
    "Unknown error 175",
    "Unknown error 176",
    "Unknown error 177",
    "Unknown error 178",
    "Unknown error 179",
    "Unknown error 180",
    "Unknown error 181",
    "Unknown error 182",
    "Unknown error 183",
    "Unknown error 184",
    "Unknown error 185",
    "Unknown error 186",
    "Unknown error 187",
    "Unknown error 188",
    "Unknown error 189",
    "Unknown error 190",
    "Unknown error 191",
    "Unknown error 192",
    "Unknown error 193",
    "Unknown error 194",
    "Unknown error 195",
    "Unknown error 196",
    "Unknown error 197",
    "Unknown error 198",
    "Unknown error 199",
    "Unknown error 200",
    "Unknown error 201",
    "Unknown error 202",
    "Unknown error 203",
    "Unknown error 204",
    "Unknown error 205",
    "Unknown error 206",
    "Unknown error 207",
    "Unknown error 208",
    "Unknown error 209",
    "Unknown error 210",
    "Unknown error 211",
    "Unknown error 212",
    "Unknown error 213",
    "Unknown error 214",
    "Unknown error 215",
    "Unknown error 216",
    "Unknown error 217",
    "Unknown error 218",
    "Unknown error 219",
    "Unknown error 220",
    "Unknown error 221",
    "Unknown error 222",
    "Unknown error 223",
    "Unknown error 224",
    "Unknown error 225",
    "Unknown error 226",
    "Unknown error 227",
    "Unknown error 228",
    "Unknown error 229",
    "Unknown error 230",
    "Unknown error 231",
    "Unknown error 232",
    "Unknown error 233",
    "Unknown error 234",
    "Unknown error 235",
    "Unknown error 236",
    "Unknown error 237",
    "Unknown error 238",
    "Unknown error 239",
    "Unknown error 240",
    "Unknown error 241",
    "Unknown error 242",
    "Unknown error 243",
    "Unknown error 244",
    "Unknown error 245",
    "Unknown error 246",
    "Unknown error 247",
    "Unknown error 248",
    "Unknown error 249",
    "Unknown error 250",
    "Unknown error 251",
    "Unknown error 252",
    "Unknown error 253",
    "Unknown error 254",
    "Unknown error 255",
    "Unknown error 256",
    "Unknown error 257",
    "Unknown error 258",
    "Unknown error 259",
    "Unknown error 260",
    "Unknown error 261",
    "Unknown error 262",
    "Unknown error 263",
    "Unknown error 264",
    "Unknown error 265",
    "Unknown error 266",
    "Unknown error 267",
    "Unknown error 268",
    "Unknown error 269",
    "Unknown error 270",
    "Unknown error 271",
    "Unknown error 272",
    "Unknown error 273",
    "Unknown error 274",
    "Unknown error 275",
    "Unknown error 276",
    "Unknown error 277",
    "Unknown error 278",
    "Unknown error 279",
    "Unknown error 280",
    "Unknown error 281",
    "Unknown error 282",
    "Unknown error 283",
    "Unknown error 284",
    "Unknown error 285",
    "Unknown error 286",
    "Unknown error 287",
    "Unknown error 288",
    "Unknown error 289",
    "Unknown error 290",
    "Unknown error 291",
    "Unknown error 292",
    "Unknown error 293",
    "Unknown error 294",
    "Unknown error 295",
    "Unknown error 296",
    "Unknown error 297",
    "Unknown error 298",
    "Unknown error 299"};

#define NUM_LINUX_ERRORS \
  (sizeof(linux_error_messages) / sizeof(linux_error_messages[0]))

#else
#error "Unknown or unsupported operating system"
#endif

const char **s21_get_error_messages() {
#ifdef __APPLE__
  return macOS_error_messages;
#elif defined(__linux__)
  return linux_error_messages;
#else
  return S21_NULL;
#endif
}

s21_size_t s21_get_num_errors() {
#ifdef __APPLE__
  return NUM_MACOS_ERRORS;
#elif defined(__linux__)
  return NUM_LINUX_ERRORS;
#else
  return 0;
#endif
}